import { useState } from 'react';
import { 
  Sparkles, Terminal, Code2, Database, ShieldCheck, 
  CheckCircle2, ArrowRight, Cpu, Bot, Check
} from 'lucide-react';
import PythonCodeHighlight from './PythonCodeHighlight';
import SqlCodeHighlight from './SqlCodeHighlight';

const SAMPLE_BIGQUERY_SQL = `-- Generated by ADK AI Data Engineer Agent (Gemini 2.5 Flash)
SELECT 
  daypart,
  APPROX_QUANTILES(winning_bid_cpm, 100)[OFFSET(90)] AS p90_clearing_cpm,
  AVG(winning_bid_cpm) AS avg_cpm,
  COUNT(1) AS total_auction_volume
FROM \`vibetube-telemetry.auctions.live_stream\`
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
GROUP BY daypart
ORDER BY p90_clearing_cpm DESC;`;

const AI_GENERATED_PYTHON_SCRIPT = `"""Vibetube Ads - AI-Optimized Bidding Policy Script
Authored by ADK AI Data Engineer Agent (Gemini 2.5 Flash) via BigQuery Telemetry.
"""

def compute_bid(context: dict) -> float:
    daypart = context.get("daypart", "morning")
    p90 = context.get("recent_p90_cpm", 2.35)
    p90_history = context.get("p90_history", [p90] * 5)
    win_rate = context.get("recent_win_rate", 0.85)
    ceiling = context.get("max_bid_ceiling", 10.00)
    budget = context.get("budget_remaining", 2500.00)
    hours = max(0.5, context.get("hours_remaining", 12.0))

    # 1. Dynamic Budget Pacing Multiplier (Target: ~$104.16 / hr)
    target_hourly = budget / hours
    pacing = min(1.2, max(0.6, target_hourly / 104.16))

    # 2. Velocity Momentum Detection from Vector Telemetry
    velocity = p90_history[-1] - p90_history[0]

    # 3. Multi-Regime Clearance & Bid Shading
    if daypart == "late_night" or velocity < -1.5:
        # Midnight cooldown: shade down to clearance floor ($0.85 P90)
        return min(0.90, ceiling)
    elif daypart == "primetime" or velocity > 1.5:
        # Aggressive evening surge: clear floor with pacing modulation
        return min((p90 + 0.05) * pacing, ceiling)
    elif daypart == "afternoon":
        # Midday & bidding war tracking
        return min((p90 + 0.05) * pacing, ceiling)
    else:
        return min(2.40, ceiling)`;

export default function AIDataEngineer({ navigate }: { navigate: (v: string) => void }) {
  const [isRunning, setIsRunning] = useState(false);
  const [agentCompleted, setAgentCompleted] = useState(false);
  const [deploying, setDeploying] = useState(false);
  const [stepIndex, setStepIndex] = useState(0);

  const handleRunAgent = async () => {
    setIsRunning(true);
    setAgentCompleted(false);
    setStepIndex(1);

    // Step 1: Tool Call 1 (query_bigquery)
    await new Promise(r => setTimeout(r, 1200));
    setStepIndex(2);

    // Step 2: Tool Call 2 (get_campaign_info)
    await new Promise(r => setTimeout(r, 1000));
    setStepIndex(3);

    // Step 3: Synthesis & Tool Call 3 (update_bidding_script)
    await new Promise(r => setTimeout(r, 1400));
    setStepIndex(4);
    setIsRunning(false);
    setAgentCompleted(true);
  };

  const handleDeployAndLaunch = async () => {
    setDeploying(true);
    try {
      await fetch('/campaign/script', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ script: AI_GENERATED_PYTHON_SCRIPT }),
      });
      navigate('simulator3');
    } catch (e) {
      console.error('Failed to deploy AI script:', e);
      navigate('simulator3');
    } finally {
      setDeploying(false);
    }
  };

  return (
    <div className="animate-rise pb-24 space-y-8 max-w-6xl mx-auto">
      {/* Page Header */}
      <div className="border-b border-hairline pb-5 flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl sm:text-4xl font-display font-bold text-fg">AI Data Engineer Studio</h1>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-3">
          {!agentCompleted ? (
            <button
              onClick={handleRunAgent}
              disabled={isRunning}
              className="px-7 py-3 bg-gradient-to-r from-vibe-cyan to-vibe-blue text-black font-bold rounded-2xl text-xs transition-all shadow-[0_0_30px_rgba(45,212,191,0.35)] hover:shadow-[0_0_45px_rgba(45,212,191,0.5)] hover:scale-105 flex items-center gap-2 cursor-pointer disabled:opacity-50"
            >
              <Sparkles size={16} className={isRunning ? "animate-spin" : ""} />
              <span>{isRunning ? 'Agent Synthesizing Policy...' : 'Run AI Data Engineer'}</span>
            </button>
          ) : (
            <button
              onClick={handleDeployAndLaunch}
              disabled={deploying}
              className="px-7 py-3 bg-emerald-400 hover:bg-emerald-300 text-black font-bold rounded-2xl text-xs transition-all shadow-[0_0_30px_rgba(52,211,153,0.4)] hover:scale-105 flex items-center gap-2 cursor-pointer disabled:opacity-50"
            >
              <span>Deploy Policy & Proceed to Step 6: Agent Simulation</span>
              <ArrowRight size={16} />
            </button>
          )}
        </div>
      </div>

      {/* 1. Declarative ADK Tools Section (Step 11 in Narrative) */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Cpu size={16} className="text-vibe-cyan" />
            <h3 className="text-sm font-bold text-fg uppercase font-mono tracking-wider">
              1. Agent Toolset (ADK 2.0 Declarative Tools)
            </h3>
          </div>
          <span className="text-xs font-mono text-fg-muted">3 Tools Bound to Gemini 2.5 Flash</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-5 bg-card border border-hairline rounded-2xl space-y-2">
            <div className="flex items-center gap-2 text-vibe-cyan font-mono font-bold text-xs">
              <Database size={15} />
              <span>query_bigquery</span>
            </div>
            <p className="text-xs text-fg-muted leading-relaxed">
              Executes windowed BigQuery standard SQL queries against real-time auction telemetry tables.
            </p>
          </div>

          <div className="p-5 bg-card border border-hairline rounded-2xl space-y-2">
            <div className="flex items-center gap-2 text-emerald-400 font-mono font-bold text-xs">
              <ShieldCheck size={15} />
              <span>get_campaign_info</span>
            </div>
            <p className="text-xs text-fg-muted leading-relaxed">
              Reads dynamic campaign state: remaining budget ($2500), flight hours left, and max bid ceiling ($10.00).
            </p>
          </div>

          <div className="p-5 bg-card border border-hairline rounded-2xl space-y-2">
            <div className="flex items-center gap-2 text-amber-400 font-mono font-bold text-xs">
              <Code2 size={15} />
              <span>update_bidding_script</span>
            </div>
            <p className="text-xs text-fg-muted leading-relaxed">
              Deploys the generated Python function to <code className="text-amber-300">bidding_policy.py</code> for live ad serving.
            </p>
          </div>
        </div>
      </div>

      {/* 2. Prompting the Agent & Live Execution Trace (Steps 12 & 13 in Narrative) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Prompting & Instructions */}
        <div className="lg:col-span-5 space-y-4">
          <div className="flex items-center gap-2">
            <Bot size={16} className="text-vibe-cyan" />
            <h3 className="text-sm font-bold text-fg uppercase font-mono tracking-wider">
              2. Agent Goal & System Prompt
            </h3>
          </div>

          <div className="p-6 bg-card rounded-3xl border border-hairline space-y-4 shadow-xl">
            <div className="space-y-1.5">
              <span className="text-[11px] font-mono font-bold text-vibe-cyan uppercase tracking-wider">
                System Persona
              </span>
              <p className="text-xs text-fg-muted font-mono leading-relaxed bg-overlay p-3 rounded-xl border border-hairline">
                "You are an expert Ad Tech Quantitative Data Engineer. Your goal is to maximize impressions won across a 24-hour campaign flight within a $2,500 budget limit."
              </p>
            </div>

            <div className="space-y-1.5">
              <span className="text-[11px] font-mono font-bold text-amber-400 uppercase tracking-wider">
                Student Instructions (User Prompt)
              </span>
              <p className="text-xs text-fg font-sans leading-relaxed bg-overlay p-3.5 rounded-xl border border-hairline">
                "Analyze clearing price dynamics across 24-hour dayparts. Author an adaptive Python bidding policy that shades bids during lull hours ($0.90), detects momentum surges with <code>p90_history</code>, and paces spend to avoid running out of money before hour 24."
              </p>
            </div>

            <div className="pt-2">
              <button
                onClick={handleRunAgent}
                disabled={isRunning}
                className="w-full py-3.5 bg-overlay hover:bg-hairline text-fg font-bold rounded-2xl text-xs border border-hairline transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
              >
                <Sparkles size={15} className="text-vibe-cyan" />
                <span>{isRunning ? 'Synthesizing with Gemini 2.5 Flash...' : agentCompleted ? 'Re-Run Agent 🔄' : 'Execute Agent Workflow'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Right Column: Execution Trace & Generated Artifacts */}
        <div className="lg:col-span-7 space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Terminal size={16} className="text-vibe-cyan" />
              <h3 className="text-sm font-bold text-fg uppercase font-mono tracking-wider">
                3. Execution Trace & Reasoning
              </h3>
            </div>
            {agentCompleted && (
              <span className="text-[11px] font-mono px-2.5 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
                <Check size={12} /> Complete
              </span>
            )}
          </div>

          <div className="p-6 bg-card rounded-3xl border border-hairline shadow-xl space-y-5">
            {/* Step Trace Timeline */}
            <div className="space-y-3 font-mono text-xs">
              <div className={`p-3 rounded-xl border transition-all space-y-2 ${
                stepIndex >= 1 ? 'bg-overlay border-vibe-cyan/40 text-fg' : 'bg-overlay/40 border-hairline text-fg-muted opacity-50'
              }`}>
                <div className="flex items-center gap-3">
                  <div className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold ${
                    stepIndex > 1 ? 'bg-emerald-400 text-black' : stepIndex === 1 ? 'bg-vibe-cyan text-black animate-pulse' : 'bg-overlay text-fg-muted'
                  }`}>
                    {stepIndex > 1 ? '✓' : '1'}
                  </div>
                  <div>
                    <span className="font-bold text-vibe-cyan">query_bigquery:</span>
                    <span className="text-fg-muted ml-1.5">Executed telemetry aggregation across 24h partitions</span>
                  </div>
                </div>

                {stepIndex >= 1 && (
                  <div className="pt-1 pl-8">
                    <div className="rounded-xl overflow-hidden border border-hairline bg-card/80">
                      <SqlCodeHighlight
                        code={SAMPLE_BIGQUERY_SQL}
                        showLineNumbers={false}
                        className="max-h-[140px]"
                      />
                    </div>
                  </div>
                )}
              </div>

              <div className={`p-3 rounded-xl border transition-all flex items-center gap-3 ${
                stepIndex >= 2 ? 'bg-overlay border-vibe-cyan/40 text-fg' : 'bg-overlay/40 border-hairline text-fg-muted opacity-50'
              }`}>
                <div className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold ${
                  stepIndex > 2 ? 'bg-emerald-400 text-black' : stepIndex === 2 ? 'bg-vibe-cyan text-black animate-pulse' : 'bg-overlay text-fg-muted'
                }`}>
                  {stepIndex > 2 ? '✓' : '2'}
                </div>
                <div>
                  <span className="font-bold text-emerald-400">get_campaign_info:</span>
                  <span className="text-fg-muted ml-1.5">Verified $2,500 budget, 24.0h flight duration, $10 ceiling</span>
                </div>
              </div>

              <div className={`p-3 rounded-xl border transition-all flex items-center gap-3 ${
                stepIndex >= 3 ? 'bg-overlay border-vibe-cyan/40 text-fg' : 'bg-overlay/40 border-hairline text-fg-muted opacity-50'
              }`}>
                <div className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold ${
                  stepIndex >= 4 ? 'bg-emerald-400 text-black' : stepIndex === 3 ? 'bg-vibe-cyan text-black animate-pulse' : 'bg-overlay text-fg-muted'
                }`}>
                  {stepIndex >= 4 ? '✓' : '3'}
                </div>
                <div>
                  <span className="font-bold text-amber-400">update_bidding_script:</span>
                  <span className="text-fg-muted ml-1.5">Generated adaptive momentum + dynamic pacing Python code</span>
                </div>
              </div>
            </div>

            {/* Generated Code Preview (shown when complete) */}
            {agentCompleted && (
              <div className="space-y-4 pt-2 border-t border-hairline animate-rise">
                <div className="space-y-2">
                  <span className="text-xs font-mono font-bold text-fg flex items-center gap-1.5">
                    <Code2 size={14} className="text-amber-400" /> Synthesized Production Policy:
                  </span>
                  <div className="rounded-2xl overflow-hidden border border-hairline bg-overlay">
                    <PythonCodeHighlight
                      code={AI_GENERATED_PYTHON_SCRIPT}
                      filename="bidding_policy.py"
                      editable={false}
                      className="max-h-[260px]"
                    />
                  </div>
                </div>

                <div className="p-4 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs font-mono text-emerald-300">
                    <CheckCircle2 size={16} className="text-emerald-400" />
                    <span>Script compiled & ready for ad server execution</span>
                  </div>
                  <button
                    onClick={handleDeployAndLaunch}
                    className="px-4 py-2 bg-emerald-400 hover:bg-emerald-300 text-black font-bold text-xs rounded-xl transition-all shadow-md cursor-pointer flex items-center gap-1.5"
                  >
                    <span>Launch Attempt 3 Simulation</span>
                    <ArrowRight size={14} />
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
